export interface User {
  id: string;
  name: string;
  email: string;
  avatar: string;
}

export enum DonationCategory {
  FOOD = 'Food',
  MEDICAL = 'Medical',
  CLOTHING = 'Clothing',
  EDUCATION = 'Education',
  OTHER = 'Other'
}

export interface Donation {
  id: string;
  userId: string;
  donorName: string;
  location: string; // UK City/Postcode
  itemsDescription: string;
  category: DonationCategory;
  weightKg: number;
  quantity: number;
  date: string;
  impactMessage?: string; // Generated by Gemini
  status: 'Pending' | 'Collected' | 'Shipped' | 'Delivered';
}

export interface DashboardStats {
  totalWeight: number;
  totalDonations: number;
  donorsCount: number;
  categoryBreakdown: { name: string; value: number }[];
  recentDonations: Donation[];
}
